/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs_jniexample_FibonacciNative */

#ifndef _Included_rtrk_pnrs_jniexample_FibonacciNative
#define _Included_rtrk_pnrs_jniexample_FibonacciNative
#ifdef __cplusplus
extern "C" {
#endif
#undef rtrk_pnrs_jniexample_FibonacciNative_GOLDEN_RATIO
#define rtrk_pnrs_jniexample_FibonacciNative_GOLDEN_RATIO 1.6180339887
#undef rtrk_pnrs_jniexample_FibonacciNative_SQRT_5
#define rtrk_pnrs_jniexample_FibonacciNative_SQRT_5 2.236067977
/*
 * Class:     rtrk_pnrs_jniexample_FibonacciNative
 * Method:    getFebonacci
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rtrk_pnrs_jniexample_FibonacciNative_getFebonacci
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
