/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativegallery_NativeAshmemBinder */

#ifndef _Included_com_example_nativegallery_NativeAshmemBinder
#define _Included_com_example_nativegallery_NativeAshmemBinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativegallery_NativeAshmemBinder
 * Method:    AshmemInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativegallery_NativeAshmemBinder_AshmemInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_nativegallery_NativeAshmemBinder
 * Method:    getImageData
 * Signature: ()[Ljava/lang/Byte;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_nativegallery_NativeAshmemBinder_getImageData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
